### ISSUE TITLE
Colour modes mess histogram

### ISSUE THREAD

**Issue by Neko250** [joshavanier/log#62] opened 2018-06-29 20:36 UTC
Here is my `.json`, for testing purposes: [hastebin.com](https://hastebin.com/rorujibiwa.json).
Using `colourmode none` makes some of the histogram entries to vanish:

### `colourmode sector`

Everything shows up with the configured colours.

![log_2018-06-29_22-28-09](https://user-images.githubusercontent.com/2650578/42113608-18af5a5e-7bec-11e8-9ead-8dbb865406a4.png)

### `colourmode project`

Everything shows up, I have no configured colours for projects.

![2018-06-29_22-28-28](https://user-images.githubusercontent.com/2650578/42113639-34d3f3ca-7bec-11e8-816f-6fbab6f26460.png)

### `colourmode none`

Here, you can see that some of the entries don't appear. 😢 

![log_2018-06-29_22-28-43](https://user-images.githubusercontent.com/2650578/42113649-4497e3e8-7bec-11e8-8593-3ea899daee1a.png)

**Comment by joshavanier** [comment] 2018-06-30 04:32
So the entries aren't displayed in the chart but they're not being deleted, right?

**Comment by Neko250** [comment] 2018-06-30 10:38
That's right.

**Comment by joshavanier** [comment] 2018-07-01 02:32
It seems the issue is already fixed here in the repo. The fix will be included in the next release

**Closed by joshavanier** 2018-07-01 02:32 UTC
